- command/deploy.go
- levant/templater.go
> command/deploy: disable templating when no variables are passed

- command/deploy.go
the previous check caused a crash if the job file lacked an update
stanza and did not check to see if only task groups contained
canary configurations instead of the job as a whole
> command/deploy: more robust canary promote check

- levant/deploy.go
> Fix issue where system jobs cause panic.

- README.md
> Update README.md to include details regarding autoload.

- levant/failure_inspector.go
failure_inspector was incorrectly handling jobs where multipule
groups were configured; printing out groups which had not had
deployment issues as well as incorrectly handling jobs where
multiple groups experienced deployment issues.
Closes #54
> Fix issue in failure_inspector incorrectly handling multi-groups.

- helper/files_test.go
> Add tests for helper/files.go

- .github/CONTRIBUTING.md
- README.md
> Add CONTRIBUTING.md within GitHub folder and add README link.

- README.md
- docs/README.md
> Add a docs directory to allow better documentation.

- levant/auto_revert.go
> Fix tiny typo

- levant/deploy.go
If, during an auto-promote run, the canary allocation(s) are
unhealthy and therefor the auto-promote will not be invoked the
auto-revert check function should not be run.
Closes #114
> Do not run the auto-revert inspector if auto-promote fails.

- README.md
- version/version.go
> Update Levant for 0.1.0 release.

- README.md
Adding line in README for the `-force-batch` flag.
> Adding force-batch docs to README

- levant/deploy.go
> Break levant/deploy function out to make smaller and cleaner.

- command/scale_in.go
speelling mistaek and message fixup :)
> typo and message fixup

- command/deploy.go
- command/render.go
> Provide better command help for deploy and render commands.

- README.md
- docs/README.md
- docs/templates.md
> Document template funcs and move template docs to docs space.

- README.md
- docs/README.md
- docs/clients.md
> Add Consul clients docs and move client docs to docs folder.

- .github/CONTRIBUTING.md
> Update contribution guide to remove ref to old build script.

- GNUmakefile
> Run tests with -race flag to detect race conditions.

- CHANGELOG.md
- Dockerfile
- README.md
- version/version.go
> Update Levant for 0.2.0 release.

- docs/templates.md
> Add documentation for new parse template functions.

- Dockerfile
- README.md
- version/version.go
> Release v0.2.1 of Levant.

- levant/failure_inspector.go
> fixed failure inspector to report on tasks that are restarting

- template/funcs.go
> Add toUpper and toLower template funcs.

- docs/templates.md
> Add documentation for toLower and toUpper template functions.

- docs/commands.md
> Add docs for plan command.

- docs/templates.md
- template/funcs.go
> Add template maths funcs: add, divide, multiply, subtract, modulo.

- levant/plan.go
Fixes #302 
Signed-off-by: M S Vishwanath Bhat <msvbhat@gmail.com>
> levant/plan: Use info level logs when no changes are detected

- docs/templates.md
- template/funcs.go
> Add template replace function

- LICENSE
> admin: update license to MPL V2 from MIT.

- levant/dispatch.go
> deploy: fix panic in dispatching parameterised job.

- README.md
Just noticed the readme is out of date ;)
> Update levant version in install instructions

- go.mod
- go.sum
> deps: update golang.org/x/crypto dependency.

- docs/commands.md
This is a smol PR that fixes a typo I noticed while reading these docs.
Thank you for the great tool.
> Fixed small typo

- test/fixtures/deploy_alloc_error.nomad
- test/fixtures/deploy_basic.nomad
- test/fixtures/deploy_canary.nomad
- test/fixtures/deploy_count.nomad
- test/fixtures/deploy_driver_error.nomad
- test/fixtures/deploy_lifecycle.nomad
- test/fixtures/deploy_task_scaling.nomad
- Remove legacy `mbits` field from resources
- Ran `hclfmt`
> [chore] Update test fixtures

- .release/ci.hcl
Match updates from https://github.com/hashicorp/nomad/blob/main/.release/ci.hcl
> ci: update ci.hcl

- docs/templates.md
> Fix typo in templates.md

- .release/levant-artifacts.hcl
> Add artifact manifest license header

- .github/workflows/build.yml
Fixes: https://github.com/hashicorp/levant/issues/510
> build: fix path for packaged artifacts
