levant/templater.go

This changes fixes two bugs introduced in 1ca427e33. The first is
that variable files extensions are not being matched due to a
change in the extension discovery which now means the `.` is
included whereas previously it was not.
The second fixes an issue where templates using a yaml/yml file
extension were not being rendered.
Closes #4
Closes #5

Fix issue with file extension parsing and yaml file rendering.

---

README.md
levant/templater.go
levant/test-fixtures/multi_templated.nomad
levant/test-fixtures/none_templated.nomad
levant/test-fixtures/single_templated.nomad

Nomad uses the standard `{{ }}` for variable interpolation which
causes conflicts if used in conjunction with Levant. This change
moves Levant to use `[[ variable]]` which removes conflicts with
standard Nomad interpolation and allows both to be used together.
Tests have been updated to check for this also.
Closes #3

Levant now uses `[[ ]]` for variable interpolation.

---

levant/templater.go
levant/templater_test.go
levant/test-fixtures/missing_var.nomad

previously the default behaviour of text/template was used which
would print the string "\<no value>", this could lead to a situation
where an job file appears valid but would fail to run
Fixes #11

templater: fail rendering if a variable is not set

---

README.md
command/deploy.go
command/render.go
commands.go
levant/templater.go
levant/templater_test.go

allows testing how the template will be rendered
Fixes #9

command: add render command

---

README.md
command/deploy.go
levant/deploy.go
levant/failure_inspector.go

Levant now supports auto promoting a canary deployment using the
-canary-auto-promote flag which accepts a value in seconds. If
after this time, Levant will check the canary alloc health, and if
healthy will promote the deployment.
Any feedback from @ericwestfall or @mimato would be appreciated.
Closes #15

 Introduce canary-auto-promote which allows for canary promotion.

---

levant/failure_inspector.go

Previously, Levant was only able to catch a small number of alloc
failure cases. This changes expands the case statement with the
ability to catch many more.
Closes #26

Update failure_inspector to cover more cases.

---

levant/deploy.go

The case statement did not have a default clause when assesssing
the Nomad job type. This caused Levant to panic on some runs as
type is not an explicit type.
The change adds a default case to catch all job types which do not
support deployments.
Closes #31

Fix a bug in handling Nomad job types incorrectly.

---

command/deploy.go
levant/deploy.go

When deploying it would be nice to have a way to force the taskgroup
count which is set in the Nomad jobfile. Currently the count is
determined based on the actively running count which is understandable
but doesn't apply for all use cases.

introduce -force-count into Deploy

---

levant/deploy.go

The switch will still lead to a SEGV as the dereference is to a nil
pointer. First verify that job.Type isn't nil.
Still the same issue as here: https://github.com/jrasell/levant/issues/31

verify job.Type isn't nil before continuing

---

levant/deploy.go

If none of the TaskGroups have a count > 0 don't continue

---

levant/deploy.go

low hanging fruit of debug output

---

levant/deploy.go

Nomad can return an evaluation which has incurred errors due to
issues such as resource starvation. Previously Levant only
checked whether an actual API error was returned from the
evaluation call which meant errors during this phase were not
caught.
This change implaments an evaluation inspector which iterates
through any errors during an evaluation to provide this feedback
to the user.
Closes #39

Update Levant deployment to inspect the evaluation results.

---

levant/deploy.go

evaluationInspector only fetched the evaluation from the API once
as the call was outside of the loop

levant: fix infinite loop with sleep

---

command/deploy_test.go
command/test-fixtures/group_canary.nomad
command/test-fixtures/job_canary.nomad

This commit adds tests for command/deploy.checkCanaryAutoPromote
to ensure both job level and taskgroup level canary stanzas are
taking into account.
@pmcatominey this may be of interest in relation to your previous PR.

Add tests for command/deploy.checkCanaryAutoPromote function.

---

levant/deploy.go

Previously Levant would register the job and then check the return
for the eval_ID and thus continue with the deployment checking.
Nomad batch jobs do not produce an evaluation upon registration
and therefore would cause an error within Levant which was not
handled in the most appropriate manner. This change checks the job
type and eval return to properly catch batch job registrations and
log correct information.
In the future Levant should be updated to perform a basic running
check on batch jobs to provide further deployment feedback.
Closes #50

Nomad jobs of type batch do not produce evaluations.

---

README.md
levant/auto_revert.go
levant/deploy.go

As of Nomad 0.6 deployments supported auto-revert; whereby a job
would be reverted to its previous stable configuration if a
deployment was marked as failed. This change introduces the
ability for Levant to track the auto-revert deployment and log
realtime feedback. Levant will also print in CAPS if either a
revert fails or a deployment failed and is not configured to
revert so that users can make adjustments to their job in future
to avoid potential outage situations.
Closes #47

Levant can now track Nomad auto-revert of a failed deployment.

---

Dockerfile

In particular setups using TLS, Levant will need the
ca-certificates package installed in order to make use of trusted
system CA certificates. Without this executing Levant results in
the error "failed to load system roots".

Update the Dockerfile to install ca-certificates for TLS envs.

---

helper/variable.go
levant/deploy.go
levant/templater.go

This change adds some logging lines to provide greater feedback to
the user around variables file passed, CLI variables passed and
which variables are being used by Levant.
Closes #61

Update logging around passed variables and overridden variables.

---

.travis.yml

This commit updates the travis.yml to only run the release build
if it is a tagged release and not on every run.

Fix issue where travis would run the release build every time.

---

command/deploy.go
command/render.go
helper/files.go
levant/templater.go

A basic way of implementing issue #10
If no argument is given we check for the existence of a
levant.nomad jobfile.
If no -var-file is given we check for the existence of a
levant.tf variable file.
This "standardizes" the use of named files and makes pipelines
clean in command usage.

autoloading of files

---

levant/deploy.go

Previously evaluationInspector only checked eval status for
exhausted resources. This changes updates the function to also
check filtered classes and constraints which might also cause
eval failures.
Closes #49

Fix issue where evaluations errors were not being fully checked.

---

levant/deploy.go
levant/job_status_checker.go

Nomad job type batch does not support the deployment model which
meant previously Levant would just exit after the job was
registered. This update adds additional functionality which means
Levant will at least confirm the job has a status of running
before exiting.
Closes #53

Add basic status checking for batch job types.

---

logging/logging.go

This addresses #68 
Note, that there are two types of log output in levant.  The first is from the UI and the second is from the various functions.  They UI uses a different logging mechanism (presumably so that they logs can be pointed to a file at somepoint while still maintaining some meaningful command output).   This only changes the function output not the UI output.  I can modify the UI output as well if you like.

added timestamp to logs

---

levant/deploy.go

if a job contains at least one task group with canary deployments configured
and at least one without, the deployment watcher will fail the deployment
as the check for healthy canaries assumed every task group is configured for
canary deployments.
Tested with `levant deploy -canary-auto-promote 30 echo.nomad` and the following Job specification (add/remove `:latest` to the image argument to trigger a deployment):
```
job "echo" {
datacenters = ["dc1"]
type = "service"
group "echo-canary" {
count = 2
update {
canary       = 2
max_parallel = 2
}
task "echo-canary" {
driver = "docker"
config {
image = "alpine"
command = "tail"
args = ["-f", "/dev/null"]
}
}
}
group "echo-standard" {
count = 1
update {
max_parallel = 1
}
task "echo-standard" {
driver = "docker"
config {
image = "alpine" …
```

levant/deploy: skip health checks for task groups without canaries

---

levant/deploy.go

This issue was caused by the incorrect assumption that jobs with a count not set or set to 0 can not result in a deployment. This was incorrect as an undefined count will result in a default count of 1; or that jobs set to count=0 can be run and deployed to stage the job or disable it.
@mimato and @adamlc this should fix the issue you're seeing and also fixes previously unseen bugs in the deployment process. It has been tested with the following suite of jobs:
* service with count 1
* service with count 0
* service with count undefined
* batch with count undefined
* batch with count 1
Closes #87

Fix issue where jobs without specified count caused panic.

---

levant/deploy.go

Batch jobs which are not either periodic or parameterized do
produce evaluations, therefore we can perform a eval status check
on these.
Tagging @dansteen 
Closes #86

Non periodic/parameterized batch jobs do produce evals to check.

---

levant/deploy.go
levant/job_status_checker.go

In the same manner that batch jobs are checked to ensure they
reach the running state; system type jobs will now go through the
same process.
Closes #92

Levant can now confirm jobs with type system reach running state.

---

levant/deploy.go

If a service job is not configured with an update stanza, no Nomad
deployment will occur. Therefore Levant must skip the deploy and
use the generic job status checker function otherwise it will
error trying to find a deployment assosiated to the register.
Closes #90

Check that service jobs have an update stanza.

---

command/deploy.go
command/meta.go
levant/auto_revert.go
levant/deploy.go
levant/failure_inspector.go
levant/job_status_checker.go
levant/structs/config.go

This commit adds a config struct to Levant which is used during
every Levant invoction. This allows for easier tracking of info
and also easier future extensibility.
Closes #95

Implement config struct for Levant to track config during run.

---

levant/deploy.go

Stopped Nomad jobs can still return through an API call and
therefore be present during the dynamicGroupCountUpdater func. In
situations where a job deployed with the same as a stopped job,
the deploymend will update the group counts based on the stopped
job which should be avoided.
Closes #105

Ensure the count updater ignores jobs that are in stopped state.

---

levant/deploy.go
levant/job_status_checker.go
levant/job_status_checker_test.go

Jobs that do not currently use Nomad deployments now go through
additional checks to provide better feedback regarding their end
state. This includes checking the job status, and any allocations
which were part of the job registration.
Closes #97

Enhanced job status checking for non-service type jobs.

---

command/deploy.go
command/deploy_test.go
command/test-fixtures/periodic_batch.nomad
levant/deploy.go
levant/structs/config.go

A new 'force-batch' boolean flag has been added to the deploy
command which allows the immediate trigger of a periodic batch job
rather than waiting for the scheduled run. This is helpful when
deploying new code as operators can see the results quickly rather
than having to wait.
Closes #107

Add 'force-batch' deploy flag to allow force run of periodic job.

---

.travis.yml

Update Levant build and release to use go 1.10

---

.travis.yml
Makefile
levant/deploy.go
levant/job_status_checker.go

This change adds misspell which performs spell checking across the
codebase. Spell checking will be triggered on travis runs and will
now fail the test if mistakes are made.

Add misspell to Makefile and run on travis runs.

---

README.md

The curl command in the README should follow redirects, and the tagged release is named `0.0.4` (without the v).

Working curl command in README

---

levant/job_status_checker.go

Fixes an issue where the allocationStatusChecker function logged
that the task was running, where the case was for the pending
state. It updates the log message to use the Nomad struct value.
Closes #130

Fix issue where allocationStatusChecker logged incorrectly.

---

command/dispatch.go
commands.go
levant/dispatch.go

Levant now has the functionality to dispatch against Nomad jobs
using the dispatch command. Jobs that are dispatched go through
the job status checker and so dispatched jobs can be confirm to
reach the running state.
Closes #113

Add Levant dispatch command to dispatch against Nomad jobs.

---

levant/failure_inspector.go

This adds a catchall to log very useful events that are not displayed anywhere else upon deployment failure.
For example:
This output isn't very helpful to developers in deploy output. There's no explanation on _why_ it failed.
```
2018/04/17 12:40:59 PDT [ERROR] levant/deploy: deployment ee8fb7f8-4277-11e8-a099-17687cc3cd50 has status failed
2018/04/17 12:40:59 PDT [ERROR] levant/failure_inspector: alloc fee09c3a-4277-11e8-b4ac-4fe73209d2f7 incurred event killed because the task was successfully killed
```
This change would add the missed events that were not picked up by the case statement.
```
2018/04/17 12:40:59 PDT [ERROR] levant/deploy: deployment ee8fb7f8-4277-11e8-a099-17687cc3cd50 has status failed
+ 2018/04/17 12:40:59 PDT [ERROR] levant/failure_inspector: alloc …
```

Add a catchall for unhandled failure cases

---

levant/job_status_checker.go
levant/job_status_checker_test.go

This resolves #149 
I have updated the jobAllocationChecker function to not delete elements out of the map so that they are still available for subsequent compares.  I have also modified the key to be a struct so that we no longer need to pre-populate our `levantTask` variable.

Fixed batch job checker

---

Dockerfile

With changes made using govvv and goreleaser it is now required
that the docker build pull the released binary from GH. This also
means the docker image uses a source of truth binary rather than
building from a checked out VCS which could be different code from
the released version if human error occurs.

Update Dockerfile to pull released artefact.

---

Dockerfile
Dockerfile.build

Recently the Dockerfile used to build the image which goes to hub
was updated to pull artefacts from GitHub releases which meant
you could no longer build images on the fly for testing. This adds
a build Dockerfile so that local changes can be built and tested.
Closes #167

Add Dockerfile.build to allow building during development.

---

.goreleaser.yml

The Levant version summary output had an erronous trailing quote
which has been resolved by correcting the goreleaser file.
Closes #166

Fix formatting issue with version summary output.

---

client/nomad.go
command/deploy.go
command/scale_in.go
command/scale_out.go
commands.go
levant/deploy.go
levant/dispatch.go
levant/structs/config.go
levant/structs/scaling.go
scale/scale.go
scale/scale_test.go

This commit is the initial commit of code to allow users to
manually scale a job in or out manually. Scaling can be done either
by a count or a percentage value with option to pass a taskgroup
name to target. If the task group is not passed, all TGs within the
job will be scaled as dictated.
```
=== RUN   TestScale_updateTaskGroup
--- PASS: TestScale_updateTaskGroup (0.00s)
=== RUN   TestScale_calculateCountBasedOnPercent
--- PASS: TestScale_calculateCountBasedOnPercent (0.00s)
PASS
```
Closes #124

Addition of scale-out and scale-in commands.

---

client/consul.go
command/deploy.go
command/deploy_test.go
command/render.go
template/funcs.go
template/render.go
template/render_test.go
template/template.go

This commit introduces template functions which allow lookups
against Consul as well as generic time lookups which are run over
the template during execution. A consul client has been added with
config flag in both the render and deploy commands as these may
need to connect to Consul for variable lookups.
Closes #58

Addition of template functions allow Consul and Time lookups.

---

README.md

Just a small typo fix in the README so the Docker Hub link works.

Fix broken Docker Hub link in README

---

README.md
docs/README.md
docs/commands.md

The commands documentation has also been moved into the docs folder
to clean up the README and make documentation easier to read and
follow.
Closes #188
Closes #17

Add documentation for scale commands and multiple var file feature

---

command/deploy.go
levant/deploy.go
levant/plan.go
levant/structs/config.go

Previously if no changes were detected on a deployment Levant
would exit with status 1 which caused some CI/CD pipeline issues.
This change allows users to change this behaviouer using the flag
whereby if no changes are detected, Levant will exit with a status
code 0.
Closes #186

Add `-ignore-no-changes` flag to deploy CLI command

---

docs/templates.md
template/funcs.go

The loop function is helpful as it allows fixed number
interations which may be desirable to users. The change also
includes a documentation update to show loop usgae.
Closes #201

Add loop template function to allow iteration in templating.

---

docs/commands.md

Update `commands.md` file with the new option to create a rendered template file

Fix option to create rendered template file

---

README.md
command/deploy.go
command/render.go
docs/templates.md
helper/files.go
template/render.go
template/template.go

Variable files can now be written in json using the .json file
extension and format. Documentation has also been updated to show
example.
Closes #208

Addition of .json as variable file format type.

---

template/funcs.go

Addition of parse* functions to help with programatic templating
of job files. The parseJSON is particulary helpful as variables
can be stored in Consul KV as a JSON block and then parsed and
used within the template job file.
Closes #209

Add additional template funcs to allow parsing of types.

---

command/deploy.go
levant/deploy.go
levant/structs/config.go

Hey! 
I tried adding an option allow-stale for deploy command for simple reasons: 
We have a pretty bad network between servers and sometimes, when we apply deploy, we get errors because nomad didn't have time to replicate the data about the deployment to neighboring servers.
Would be happy to receive your feedback!

Added -allow-stale option into deploy

---

levant/deploy.go

Previously if an eval included information about filtered nodes
the deployment would show as failed even if the non-filtered evals
placed successfully. This change means Levant will not fail when
evals are filtered and will continue to track the rest of the
deployment.
Closes #220

Do not fail a deployment when nodes have been filtered during eval.

---

command/plan.go
commands.go
levant/deploy.go
levant/dispatch.go
levant/job_status_checker.go
levant/plan.go
levant/structs/config.go
scale/scale.go

When performing larger job changes; Nomad plan provides useful
insights into what changes will happen. Previously Levant would run
a plan during the deploy command run, but would move straight onto
the deploy part. The plan command addition means you can render a
templated job and see what changes will be made without triggering
a deployment.
Closes #229

Add plan command to allow running a plan whilst using templating.

---

scale/scale.go

@jrasell Hey, there was a simple NPE bug 😃  in the most recent release causing NPEs on scale outs
```
func Test_BadCode(t *testing.T) {
job := &nomad.Job{}
deploymentConfig := &levant.DeployConfig{}
deploymentConfig.Template.Job = job
deploymentConfig.Deploy.ForceCount = true
}
func Test_GoodCode(t *testing.T) {
job := &nomad.Job{}
deploymentConfig := &levant.DeployConfig{}
deploymentConfig.Template = &structs.TemplateConfig{Job: job}
deploymentConfig.Deploy = &structs.DeployConfig{ForceCount: true}
}
```
I think this change should be merged asap. Our deploys crashed in production with:
```
2018-10-05T14:11:59Z |INFO| levant/scale: task group api-nomad-prod-hostnet will scale-out from 300 to 350 job_id=api-nomad
panic: runtime error: invalid memory address or nil pointer dereference …
```

Fix NPE - seems like a missing initialization

---

levant/deploy.go

Jobs with count 0 do not produce deployments and therefore when
performing a deployment with a count of zero Levant would hang
attempting to track a deployment which would never occur. This
introduces a checker to see whether the job has any taskgroups
with a count greater than zero.
Closes #243

Fix bug where job deploys with count 0 hang.

---

CHANGELOG.md
Dockerfile
levant/deploy.go
version/version.go

When checking if a taskgroup count was greater than zero, it did
not account for the potential for it to be nil, when a count is
not specified and uses the default 1. This fixes that bug and
releases 0.2.5 as an emergency fix.
Closes #248

Fix panic in deployment due to unsafe count checking on taskgroups

---

command/deploy.go
command/plan.go
levant/plan.go

Based on documentation, this flag should not invoke deployment when job hasn't changes, only return '0' code rather then '1'.

Fix miss behavior when flag 'ignore-no-changes' was set.

---

Gopkg.lock
levant/deploy.go
vendor/github.com/pkg/errors/.gitignore
vendor/github.com/pkg/errors/.travis.yml
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/README.md
vendor/github.com/pkg/errors/appveyor.yml
vendor/github.com/pkg/errors/bench_test.go
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/errors_test.go
vendor/github.com/pkg/errors/example_test.go
vendor/github.com/pkg/errors/format_test.go
vendor/github.com/pkg/errors/stack.go
vendor/github.com/pkg/errors/stack_test.go

In situations where the deployed evaluations didn't invoke a
deployment, the return from the Nomad eval endpoint would include
an empty deployment ID. Levant would continue to retry until the
deployment ID object was populated, which possibly wouldn't
happen causing Levant to get stuck in a loop forever.
This change adds a timeout into the function which performs the
above work, so that if after 60s no deployment ID has been
returned, Levant will exit with a useful message.
Closes #263

Fix deploy loop bug when evaluation didn't include a deployment ID.

---

docs/commands.md

There was a small typo I noticed in the `commands.md` descriptions of log-level. It suggests `WARNING` is a valid option but it is actually `WARN`. https://github.com/jrasell/levant/blob/fc29298e3019a04750c3c51ae9484becdcd3f586/logging/logging.go#L16

Fix typo in log level documentation

---

template/render_test.go
template/template.go

When performing complex template rendering, it is helpful to be
able to perform if statements based on the existence of a passed
variable like `if .env`. The template runs fine if the variable
is passed, but if it isn't the execution will stop because of the
missingkey setting. This change proposes setting the missingkey
value to zero rather than error. This means that rather than error
out, the operation returns the zero value for the map type's
element and the render execution can continue.

Use missingkey=zero rather than error in template rendering.

---

test/acctest/acctest.go
test/acctest/deploy.go
test/deploy_test.go
test/fixtures/deploy_basic.nomad
test/fixtures/deploy_failure.nomad

Following on from #51, this PR implements some basic integration tests. Also includes a small testing framework in a similar fashion to Terraform provider acceptance tests to make writing tests simple.
To run, start a Nomad agent in dev mode and run:
```sh
go test -timeout 120s github.com/jrasell/levant/test -v
```

test: add basic integration tests

---

test/acctest/acctest.go
test/acctest/deploy.go
test/deploy_test.go
test/fixtures/deploy_alloc_error.nomad
test/fixtures/deploy_canary.nomad
test/fixtures/deploy_count.nomad
test/fixtures/deploy_driver_error.nomad

Fixes #51.
```
=== RUN   TestDeploy_basic
--- PASS: TestDeploy_basic (14.45s)
=== RUN   TestDeploy_driverError
--- PASS: TestDeploy_driverError (20.30s)
=== RUN   TestDeploy_allocError
--- PASS: TestDeploy_allocError (20.29s)
=== RUN   TestDeploy_count
--- PASS: TestDeploy_count (26.01s)
=== RUN   TestDeploy_canary
--- PASS: TestDeploy_canary (17.39s)
PASS
ok  	github.com/jrasell/levant/test	98.459s
```

test: add count and canary integration tests

---

command/scale_in.go

Error message for scale-in command actually says "You must set either -count or -percent flag to **scale-out**"

Fix typo in error message

---

levant/deploy.go

Use `depID` instead, which was defined before.

Fix segfault when accessing dep, which is nil on error.

---

CHANGELOG.md
GNUmakefile
command/deploy.go
docs/commands.md
levant/structs/config.go

In some cases it is necessary to deploy a version that was already
deployed. For example, when something unexpected happened
on the Nomad side and not all allocations come up.
To mitigate that, the `force` flag triggers a deployment without
running `plan` before and just blindly forwards the command
to Nomad.

Add force flag to trigger a deployment even without changes

---

Dockerfile

Runs the container as a binary, so the `docker run` command is `docker run jrasell/levant [--version] [--help] <command> [<args>]`:
```
➜ docker run jrasell/levant version
Levant v0.2.7
Date: 2019-03-19T08:26:24Z
Commit: 9e952d55f171e63f5c7955e826401eac91ed0b28
Branch: 0.2.7
State: 0.2.7
Summary: 9e952d55f171e63f5c7955e826401eac91ed0b28
```
Instead of `docker run jrasell/levant levant [--version] [--help] <command> [<args>]`:
```
$ docker run jrasell/levant levant version
...
```

Set entrypoint as levant

---

README.md

Added installation instruction via go toolkit (useful for macOS users).
(+ fixed git clone command)

Installation tip for macOS

---

README.md
go.mod
template/funcs.go

This PR adds go-spew to provide a spewDump and spewPrintf template function, which can be used in the process of template development or debugging.
I am totally flexible on what we call the functions.  Future work might include the ability to provide a spew configuration.
I have this based on f-move-all-the-things to be prepared for its merge to master.

[feature] Adding spew for debugging

---

README.md
command/render.go
docs/commands.md
test.levant

Render always emits logs in debug level and JSON format.  Adding these flags to allow operators to change this up.  
Defaulted to existing behavior, even though it is inconsistent with the defaults on other commands. Personally, I'd prefer to adopt the defaults the other commands use as the defaults for render, but that would be a breaking change.

Add log-level and log-format flags to `render`

---

command/render.go

Currently the render command logs at DEBUG in JSON format.  This PR would make the log level consistent with the other Levant commands.  It is a change in behavior so I isolated it as its own PR.

Making render logging consistent with other commands

---

docs/templates.md

docs: fix template examples with easier and usable examples.

---

docs/README.md

Fix a typo in the sub-title of the documentation README

Fix typo in README sub-title

---

levant/job_status_checker.go

Pass the namespace to the query options when querying for the job status. Resolves #333

Pass the namespace in job_status_checker

---

helper/nomad/opts.go
helper/nomad/opts_test.go
levant/job_status_checker.go

job-checker: fix panic where job namespace is not set.

---

.gitignore
template/funcs.go

This PR changes the default function implementations to Sprig anyplace that there's a conflict.  The levant implementations are decorated with levant and upcased first letter of the function name, for example, the levant `env` function is renamed to `levantEnv`
Includes drive-by fix to add .DS_Store to .gitignore.

Switching default implementations to Sprig

---

command/deploy_test.go
command/meta.go
go.mod
helper/kvflag.go
helper/kvflag_test.go
helper/variable.go
helper/variable_test.go
template/render.go
template/render_test.go
template/template.go
test/acctest/deploy.go
test/deploy_test.go

This change updates the way the var CLI flag is processed to allow
the use of nested variables in the form of nested.var=val. Until
now either side of the delimiter was evaluated simply as a string.
All tests have been updated and accomodate the change aongside the
acceptance tests.
closes #257

cli: allow nested variables to be passed via var CLI flag.

---

template/render_test.go

I have no idea how this was not caught by CI.

test: fixup broken test.

---

CHANGELOG.md
logging/logging.go

seems like the simplest way to address this. i couldn't think of a scenario where a user would have been relying on logging going with the rendered file to stdout.

if stdout isn't a terminal, send logging to stderr

---

docs/templates.md

A small PR fixing a word typo in templates documentation

Fix doc typo

---

README.md

Fixes https://github.com/hashicorp/levant/issues/432
The Download & Install instructions are accurate but the order of
those instructions makes it easy for someone to start by downloading
older versions via `curl` and then miss the further instructions for
downloading current versions and official builds.
Move the HashiCorp releases option to be first, move the older version
releases to be last, and clean up the `go install` invocation.

docs: clarify source for official release binaries

---

levant/plan.go

The option name is listed incorrectly (backwards, in fact) in the output of plan.

Typo in plan output

---

docs/templates.md

The phrase "Batman and Robin" should be piped into `replace` or set as the last parameter.  Closes #419

Update example for `replace` function.

---

.github/workflows/nightly-release.yml

The GHA version pinning PR upgraded several actions to their latest version, causing `actions/github-script` to fail due to some breaking changes.
Failed run: https://github.com/hashicorp/levant/actions/runs/4793342895
Successful run: https://github.com/hashicorp/levant/actions/runs/4853528583

ci: fix nightly release

---

command/deploy.go
command/plan.go

There is no more -job-file argument, so this help text is misleading.

There is no more -job-file argument

---

.github/workflows/actionlint.yml
.github/workflows/build.yml
.github/workflows/ci.yml
.github/workflows/nightly-release.yml

Part of removing any actions that might still use the Node 16 actions.
* actions/checkout v4.1.1 ==> v4.1.6
* actions/download-artifact v3.0.2 ==> v4.1.7
* actions/github-script v6.4.1 ==> v7.0.1
* actions/setup-go v4.1.0 ==> v5.0.1
* actions/upload-artifact v4.3.1 ==> v4.3.3
* eregon/publish-release v1.0.5 ==> v1.0.6
* ncipollo/release-action v1.13.0 ==> v1.14.0
* hashicorp/actions-docker-build v1.0.0 ==> v2.0.0
* hashicorp/actions-generate-metadata v1.0.0 ==> v1.1.1
* hashicorp/actions-go-build v0.1.9 ==> v1.0.0
* hashicorp/actions-slack-status v1.0.0 ==> v2.0.1

Update GitHub actions to current

---

Dockerfile
levant/deploy.go

This change uses the namespace from the rendered Levant template in order to lookup any pre-existing job with the same name in the Nomad API.
Fixes hashicorp/levant#553

Make Levant deploys namespace-aware for detecting existing Nomad jobs
